# Generated by Django 6.0.2 on 2026-03-05 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_usuarios_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosistema',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
        migrations.RenameIndex(
            model_name='usuariosistema',
            new_name='idx_usuarios_correo',
            old_name='usuario_correo_idx',
        ),
        migrations.RenameIndex(
            model_name='usuariosistema',
            new_name='idx_usuarios_rol',
            old_name='usuario_rol_idx',
        ),
        migrations.RenameIndex(
            model_name='usuariosistema',
            new_name='idx_usuarios_activo',
            old_name='usuario_activo_idx',
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si la cuenta está activa'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='activo_logico',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente (soft delete)'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='correo',
            field=models.EmailField(db_index=True, help_text='Correo electrónico único del usuario', max_length=200, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de última modificación', null=True),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='nombre_completo',
            field=models.CharField(help_text='Nombre completo del usuario', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='password_hash',
            field=models.CharField(help_text='Hash PBKDF2 o similar de la contraseña', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('VISITADOR_TECNICO', 'Visitador Técnico')], db_index=True, default='FUNCIONARIO', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to='database.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_modificados', to='database.usuariosistema'),
        ),
        migrations.AddIndex(
            model_name='usuariosistema',
            index=models.Index(fields=['rol', 'activo'], name='idx_usuarios_rol_activo'),
        ),
        migrations.AddConstraint(
            model_name='usuariosistema',
            constraint=models.UniqueConstraint(condition=models.Q(('activo_logico', True)), fields=('correo',), name='uk_usuarios_correo'),
        ),
    ]
