# Generated by Django 6.0.2 on 2026-03-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_usuariosistema_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('TECNICO_VISITANTE', 'Técnico Visitante')], db_index=True, help_text='Nombre único del rol', max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del rol', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Rol del Sistema',
                'verbose_name_plural': 'Roles del Sistema',
                'db_table': 'roles',
            },
        ),
        migrations.RemoveIndex(
            model_name='usuariosistema',
            name='idx_usuarios_rol',
        ),
        migrations.RemoveIndex(
            model_name='usuariosistema',
            name='idx_usuarios_rol_activo',
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to='database.usuariosistema'),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de eliminación (soft delete)', null=True),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, db_column='usuario_eliminacion', help_text='Usuario que eliminó este registro (soft delete)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_eliminados', to='database.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='usuario_modificacion', help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_modificados', to='database.usuariosistema'),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', help_text='Rol del usuario en el sistema', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.rol'),
        ),
        migrations.AddIndex(
            model_name='usuariosistema',
            index=models.Index(fields=['id_rol'], name='idx_usuarios_id_rol'),
        ),
        migrations.AddIndex(
            model_name='usuariosistema',
            index=models.Index(fields=['id_rol', 'activo'], name='idx_usuarios_id_rol_activo'),
        ),
        migrations.RemoveField(
            model_name='usuariosistema',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuariosistema',
            name='usuario_creacion',
        ),
    ]
