# Generated by Django 6.0.2 on 2026-03-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rol_remove_usuariosistema_idx_usuarios_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=2, help_text='Rol del usuario en el sistema', on_delete=django.db.models.deletion.RESTRICT, to='database.rol'),
        ),
    ]
