# Generated by Django 6.0.2 on 2026-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_usuariosistema_id_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de documento/cédula del usuario', max_length=20, null=True),
        ),
    ]
