# Generated by Django 6.0.2 on 2026-03-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_formularios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoformulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formularioetapa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CEDULA_CIUDADANIA', 'Cédula de ciudadanía'), ('CEDULA_EXTRANJERIA', 'Cédula de extranjería'), ('TARJETA_IDENTIDAD', 'Tarjeta de identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO_CIVIL', 'Registro civil'), ('PERMISO_PROTECCION_TEMPORAL', 'Permiso protección temporal')], max_length=30)),
                ('numero_documento', models.CharField(max_length=30)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('INTERSEXUAL', 'Intersexual')], max_length=15)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=150, null=True)),
                ('departamento_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('municipio_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadanos', to='database.formularioetapa')),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'db_table': 'ciudadanos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
