# Generated by Django 6.0.2 on 2026-03-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_postulacion_estado_default_en_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('SUBSANACION', 'Subsanación'), ('VISITA_PENDIENTE', 'Visita pendiente'), ('VISITA_REALIZADA', 'Visita realizada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_REVISION', max_length=20),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('visita_efectiva', models.BooleanField()),
                ('motivo_no_efectiva', models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('RECHAZO_VISITA', 'Rechazo de visita'), ('DIRECCION_NO_ENCONTRADA', 'Dirección no encontrada'), ('OTRO', 'Otro')], max_length=30, null=True)),
                ('motivo_no_efectiva_otro', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_encuestado', models.CharField(blank=True, default='', max_length=200)),
                ('numero_documento_encuestado', models.CharField(blank=True, default='', max_length=30)),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=30)),
                ('acta_firmada', models.CharField(blank=True, default='', max_length=500)),
                ('observaciones_generales', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('activo_logico', models.BooleanField(default=True)),
                ('encuestador', models.ForeignKey(db_column='id_encuestador', on_delete=django.db.models.deletion.RESTRICT, related_name='visitas_asignadas', to='database.usuariosistema')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='database.etapa')),
                ('id_encuestador_creacion', models.ForeignKey(db_column='id_encuestador_creacion', on_delete=django.db.models.deletion.PROTECT, related_name='visitas_creadas', to='database.usuariosistema')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='database.miembrohogar')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='database.postulacion')),
                ('usuario_eliminacion', models.ForeignKey(blank=True, db_column='usuario_eliminacion_visita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_eliminadas', to='database.usuariosistema')),
                ('usuario_modificacion', models.ForeignKey(blank=True, db_column='usuario_modificacion_visita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_modificadas', to='database.usuariosistema')),
                ('usuario_validacion', models.ForeignKey(blank=True, db_column='usuario_validacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_validadas', to='database.usuariosistema')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVisitaEtapa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RECIBO_PREDIAL', 'Recibo predial'), ('CERTIFICADO_TRADICION_LIBERTAD', 'Certificado de tradición y libertad'), ('ESCRITURA_PUBLICA', 'Escritura pública'), ('CONTRATO_ARRENDAMIENTO', 'Contrato de arrendamiento'), ('RECIBO_AGUA', 'Recibo de agua'), ('RECIBO_ENERGIA', 'Recibo de energía'), ('RECIBO_GAS', 'Recibo de gas'), ('OTRO', 'Otro')], max_length=50)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=300)),
                ('archivo', models.FileField(upload_to='documentos/visitas_e2/%Y/%m/')),
                ('ruta_archivo', models.CharField(blank=True, default='', max_length=500)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('activo_logico', models.BooleanField(default=True)),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga_doc_e2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_visita_e2_cargados', to='database.usuariosistema')),
                ('usuario_eliminacion', models.ForeignKey(blank=True, db_column='usuario_eliminacion_doc_e2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_visita_e2_eliminados', to='database.usuariosistema')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_etapa2', to='database.visita')),
            ],
            options={
                'verbose_name': 'Documento de Visita Etapa 2',
                'verbose_name_plural': 'Documentos de Visita Etapa 2',
                'db_table': 'documentos_visita_etapa2',
            },
        ),
        migrations.CreateModel(
            name='DatosHogarEtapa2',
            fields=[
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datos_hogar', serialize=False, to='database.visita')),
                ('foto_predio_url', models.CharField(blank=True, default='', max_length=500)),
                ('calidad_tenencia', models.CharField(blank=True, choices=[('PROPIETARIO', 'Propietario'), ('POSEEDOR', 'Poseedor'), ('ARRENDATARIO', 'Arrendatario'), ('USUFRUCTUARIO', 'Usufructuario')], default='', max_length=20)),
                ('tiene_escrituras', models.BooleanField(blank=True, null=True)),
                ('tiene_certificado_libertad', models.BooleanField(blank=True, null=True)),
                ('tiene_contrato_arrendamiento', models.BooleanField(blank=True, null=True)),
                ('uso_inmueble', models.CharField(blank=True, choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('MIXTO', 'Mixto'), ('INSTITUCIONAL', 'Institucional')], default='', max_length=20)),
                ('rango_ingresos_hogar', models.CharField(blank=True, choices=[('MENOS_1_SMMLV', 'Menos de 1 SMMLV'), ('1_A_2_SMMLV', '1 a 2 SMMLV'), ('2_A_4_SMMLV', '2 a 4 SMMLV'), ('MAS_4_SMMLV', 'Más de 4 SMMLV')], default='', max_length=20)),
                ('hay_adultos_mayores', models.BooleanField(blank=True, null=True)),
                ('hay_personas_discapacidad', models.BooleanField(blank=True, null=True)),
                ('hay_madre_cabeza_hogar', models.BooleanField(blank=True, null=True)),
                ('hay_victimas_conflicto', models.BooleanField(blank=True, null=True)),
                ('material_pisos', models.CharField(blank=True, choices=[('TIERRA', 'Tierra'), ('CEMENTO', 'Cemento'), ('BALDOSA', 'Baldosa'), ('MADERA', 'Madera'), ('OTRO', 'Otro')], default='', max_length=20)),
                ('material_paredes', models.CharField(blank=True, choices=[('BAHAREQUE', 'Bahareque'), ('MADERA', 'Madera'), ('BLOQUE_LADRILLO', 'Bloque/Ladrillo'), ('PREFABRICADO', 'Prefabricado'), ('OTRO', 'Otro')], default='', max_length=20)),
                ('numero_habitaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('tiene_agua', models.BooleanField(blank=True, null=True)),
                ('tiene_energia', models.BooleanField(blank=True, null=True)),
                ('tiene_gas', models.BooleanField(blank=True, null=True)),
                ('tiene_alcantarillado', models.BooleanField(blank=True, null=True)),
                ('percepcion_seguridad', models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='', max_length=10)),
                ('riesgo_inundacion', models.BooleanField(blank=True, null=True)),
                ('riesgo_deslizamiento', models.BooleanField(blank=True, null=True)),
                ('riesgo_estructural', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, db_column='usuario_creacion_datos_e2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_hogar_e2_creados', to='database.usuariosistema')),
                ('usuario_modificacion', models.ForeignKey(blank=True, db_column='usuario_modificacion_datos_e2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_hogar_e2_modificados', to='database.usuariosistema')),
            ],
            options={
                'verbose_name': 'Datos de Hogar Etapa 2',
                'verbose_name_plural': 'Datos de Hogar Etapa 2',
                'db_table': 'datos_hogar_etapa2',
            },
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['postulacion'], name='idx_visita_postulacion'),
        ),
    ]
