# Generated by Django 6.0.2 on 2026-03-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_visitas_etapa2'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZANDO', 'Realizando'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo_visita',
            field=models.CharField(blank=True, choices=[('INICIAL', 'Inicial'), ('SEGUIMIENTO', 'Seguimiento'), ('VERIFICACION', 'Verificación'), ('FINAL', 'Final')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='encuestador',
            field=models.ForeignKey(blank=True, db_column='id_encuestador', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visitas_asignadas', to='database.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='database.etapa'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_visita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='id_encuestador_creacion',
            field=models.ForeignKey(blank=True, db_column='id_encuestador_creacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_creadas', to='database.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='visita_efectiva',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
