# Generated by Django 6.0.2 on 2026-03-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_postulacion_funcionario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentovisitaetapa2',
            name='tipo_documento',
            field=models.CharField(choices=[('RECIBO_PREDIAL', 'Recibo predial'), ('CERTIFICADO_TRADICION_LIBERTAD', 'Certificado de tradición y libertad'), ('ESCRITURA_PUBLICA', 'Escritura pública'), ('CONTRATO_ARRENDAMIENTO', 'Contrato de arrendamiento'), ('RECIBO_AGUA', 'Recibo de agua'), ('RECIBO_ENERGIA', 'Recibo de energía'), ('RECIBO_GAS', 'Recibo de gas'), ('FOTO_VISITA', 'Foto de la visita'), ('INFORME_TECNICO', 'Informe técnico'), ('ACTA_VISITA', 'Acta de visita'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='LlamadaPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llamada', models.DateField()),
                ('hora_llamada', models.TimeField()),
                ('resultado', models.CharField(choices=[('CONTESTADA', 'Contestada'), ('NO_CONTESTA', 'No contesta'), ('BUZON', 'Buzón de voz'), ('NUMERO_EQUIVOCADO', 'Número equivocado'), ('NUMERO_FUERA_SERVICIO', 'Número fuera de servicio')], max_length=30)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo_logico', models.BooleanField(default=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='database.postulacion')),
                ('usuario_llamada', models.ForeignKey(db_column='usuario_llamada', on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_realizadas', to='database.usuariosistema')),
            ],
            options={
                'verbose_name': 'Llamada a Postulante',
                'verbose_name_plural': 'Llamadas a Postulantes',
                'db_table': 'llamadas_postulacion',
                'ordering': ['-fecha_llamada', '-hora_llamada'],
                'indexes': [models.Index(fields=['postulacion'], name='idx_llamada_postulacion')],
            },
        ),
    ]
