# Generated by Django 6.0.2 on 2026-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_llamada_postulacion_y_nuevos_tipos_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
