# Generated by Django 6.0.2 on 2026-03-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_etapa_finalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos', models.JSONField(default=dict, help_text='Dict: { campo_id: { "requerido": bool, "habilitado": bool } }')),
                ('publicado', models.BooleanField(default=False, help_text='True cuando el gestor ha publicado el formulario de visita técnica.')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_visita_tecnica', to='database.etapa')),
            ],
            options={
                'verbose_name': 'Configuración Visita Técnica',
                'verbose_name_plural': 'Configuraciones Visita Técnica',
                'db_table': 'config_visita_tecnica',
            },
        ),
    ]
