# Generated by Django 6.0.2 on 2026-03-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_configgestiondocumental'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcesoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ACTA_VISITA_TECNICA', 'Acta de visita técnica'), ('FORMULARIO_UNICO_NACIONAL', 'Formulario único nacional'), ('RADICADO_CURADURIA', 'Radicado de curaduría'), ('EXPENSA_RADICACION_INICIAL', 'Expensa de radicación inicial'), ('EXPENSA_LICENCIA_FINAL', 'Expensa de licencia final'), ('PODER_AUTENTICADO', 'Poder autenticado'), ('INFORME_TECNICO_VALIDACION', 'Informe técnico de validación'), ('APROBACION_MINVIVIENDA', 'Aprobación MinVivienda'), ('OFICIO_CONSTRUCTOR', 'Oficio del constructor'), ('TARJETA_PROFESIONAL_CONSTRUCTOR', 'Tarjeta profesional del constructor'), ('CERTIFICACION_EXPERIENCIA', 'Certificación de experiencia'), ('PLANOS_LEVANTAMIENTO_PDF', 'Planos de levantamiento (PDF)'), ('PLANOS_LEVANTAMIENTO_DWG', 'Planos de levantamiento (DWG)'), ('PLANOS_ARQUITECTONICOS_PDF', 'Planos arquitectónicos (PDF)'), ('PLANOS_ARQUITECTONICOS_DWG', 'Planos arquitectónicos (DWG)'), ('PLANOS_ESTRUCTURALES_PDF', 'Planos estructurales (PDF)'), ('PLANOS_ESTRUCTURALES_DWG', 'Planos estructurales (DWG)'), ('FOTO_VALLA_CURADURIA', 'Foto de valla de curaduría'), ('PRESUPUESTO_PDF', 'Presupuesto de obra (PDF)'), ('PRESUPUESTO_XLSX', 'Presupuesto de obra (Excel)'), ('OFICIO_USO_SUELOS', 'Oficio de uso de suelos'), ('CONCEPTO_GESTION_RIESGO', 'Concepto de gestión de riesgo'), ('RIESGO_INUNDACION_REMOCION', 'Riesgo de inundación / remoción masa'), ('CERTIFICACION_AGUA', 'Certificación de agua'), ('CERTIFICACION_ENERGIA', 'Certificación de energía')], max_length=50)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=300)),
                ('archivo', models.FileField(upload_to='documentos/proceso_interno/%Y/%m/')),
                ('ruta_archivo', models.CharField(blank=True, default='', max_length=500)),
                ('numero_radicado_orfeo_solicitud', models.CharField(blank=True, default='', max_length=50)),
                ('numero_radicado_orfeo_respuesta', models.CharField(blank=True, default='', max_length=50)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('activo_logico', models.BooleanField(default=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proceso_interno', to='database.postulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, db_column='usuario_creacion_doc_pi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_proceso_creados', to='database.usuariosistema')),
                ('usuario_eliminacion', models.ForeignKey(blank=True, db_column='usuario_eliminacion_doc_pi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_proceso_eliminados', to='database.usuariosistema')),
                ('usuario_modificacion', models.ForeignKey(blank=True, db_column='usuario_modificacion_doc_pi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_proceso_modificados', to='database.usuariosistema')),
            ],
            options={
                'verbose_name': 'Documento de Proceso Interno',
                'verbose_name_plural': 'Documentos de Proceso Interno',
                'db_table': 'documentos_proceso_interno',
                'indexes': [models.Index(fields=['postulacion'], name='idx_doc_pi_postulacion')],
            },
        ),
    ]
