# Generated by Django 6.0.2 on 2026-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_add_documentos_cargados_beneficiado_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('SUBSANACION', 'Subsanación'), ('VISITA_PENDIENTE', 'Visita pendiente'), ('VISITA_REALIZADA', 'Visita realizada'), ('DOCUMENTOS_INCOMPLETOS', 'Documentos incompletos'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('BENEFICIADO', 'Beneficiado'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_REVISION', max_length=25),
        ),
    ]
