# Generated by Django 6.0.2 on 2026-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_add_no_beneficiario_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('INHABILITADO', 'Inhabilitado'), ('CULMINADO', 'Culminado')], default='BORRADOR', max_length=20),
        ),
    ]
