# Generated by Django 6.0.2 on 2026-04-09 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_miembroholgar_sexo_telefono_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LlamadaPostulacion',
            new_name='LlamadaVisita',
        ),
        migrations.AlterModelOptions(
            name='llamadavisita',
            options={
                'verbose_name': 'Llamada de Visita',
                'verbose_name_plural': 'Llamadas de Visita',
                'db_table': 'llamadas_visita',
                'ordering': ['-fecha_llamada', '-hora_llamada'],
            },
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('SUBSANACION', 'Subsanación'), ('VISITA_PENDIENTE', 'Visita pendiente'), ('VISITA_PROGRAMADA', 'Visita programada'), ('VISITA_REALIZADA', 'Visita realizada'), ('DOCUMENTOS_INCOMPLETOS', 'Documentos incompletos'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('BENEFICIADO', 'Beneficiado'), ('NO_BENEFICIARIO', 'No beneficiario'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_REVISION', max_length=25),
        ),
    ]
