# Generated by Django 6.0.2 on 2026-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_llamadavisita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprocesointerno',
            name='tipo_documento',
            field=models.CharField(choices=[('ACTA_VISITA_TECNICA', 'Acta de visita técnica'), ('FORMULARIO_UNICO_NACIONAL', 'Formulario único nacional'), ('RADICADO_CURADURIA', 'Radicado de curaduría'), ('EXPENSA_RADICACION_INICIAL', 'Expensa de radicación inicial'), ('EXPENSA_LICENCIA_FINAL', 'Expensa de licencia final'), ('PODER_AUTENTICADO', 'Poder autenticado'), ('INFORME_TECNICO_VALIDACION', 'Informe técnico de validación'), ('APROBACION_MINVIVIENDA', 'Aprobación MinVivienda'), ('OFICIO_CONSTRUCTOR', 'Oficio del constructor'), ('TARJETA_PROFESIONAL_CONSTRUCTOR', 'Tarjeta profesional del constructor'), ('CERTIFICACION_EXPERIENCIA', 'Certificación de experiencia'), ('PLANOS_LEVANTAMIENTO_PDF', 'Planos de levantamiento (PDF)'), ('PLANOS_LEVANTAMIENTO_DWG', 'Planos de levantamiento (DWG)'), ('PLANOS_ARQUITECTONICOS_PDF', 'Planos arquitectónicos (PDF)'), ('PLANOS_ARQUITECTONICOS_DWG', 'Planos arquitectónicos (DWG)'), ('PLANOS_ESTRUCTURALES_PDF', 'Planos estructurales (PDF)'), ('PLANOS_ESTRUCTURALES_DWG', 'Planos estructurales (DWG)'), ('FOTO_VALLA_CURADURIA', 'Foto de valla de curaduría'), ('PRESUPUESTO_PDF', 'Presupuesto de obra (PDF)'), ('PRESUPUESTO_XLSX', 'Presupuesto de obra (Excel)'), ('OFICIO_USO_SUELOS', 'Oficio de uso de suelos'), ('CONCEPTO_GESTION_RIESGO', 'Concepto de gestión de riesgo'), ('RIESGO_INUNDACION_REMOCION', 'Riesgo de inundación / remoción masa'), ('CERTIFICACION_AGUA', 'Certificación de agua'), ('CERTIFICACION_ENERGIA', 'Certificación de energía'), ('ORFEO_SOLICITUD', 'Orfeo solicitud'), ('ORFEO_RESPUESTA', 'Orfeo respuesta')], max_length=50),
        ),
    ]
