# Generated by Django 6.0.2 on 2026-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_alter_documentoprocesointerno_tipo_documento'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='llamadavisita',
            name='idx_llamada_visita',
        ),
        migrations.DeleteModel(
            name='LlamadaVisita',
        ),
    ]
