# Generated by Django 6.0.2 on 2026-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_remove_llamadavisita_idx_llamada_visita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('SUBSANACION', 'Subsanación'), ('VISITA_PENDIENTE', 'Visita pendiente'), ('VISITA_ASIGNADA', 'Visita asignada'), ('VISITA_PROGRAMADA', 'Visita programada'), ('VISITA_REALIZADA', 'Visita realizada'), ('DOCUMENTOS_INCOMPLETOS', 'Documentos incompletos'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('BENEFICIADO', 'Beneficiado'), ('NO_BENEFICIARIO', 'No beneficiario'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_REVISION', max_length=25),
        ),
    ]
