# Generated by Django 6.0.2 on 2026-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_add_visita_asignada_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada'), ('PROGRAMADA', 'Programada'), ('REALIZANDO', 'Realizando'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20),
        ),
    ]
