# Generated by Django 6.0.2 on 2026-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_add_inhabilitado_config_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionhogaretapa1',
            name='documentos_incorrectos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
