#!/usr/bin/env python
"""
seed_mi_casa3.py
================
Inserta 10 postulaciones completas para el programa "Mi casa3" (id=13).

Cada postulación incluye:
  • Ciudadano titular
  • Postulacion (estado EN_REVISION)
  • GestionHogarEtapa1 (datos de ubicación y predio en Popayán, Cauca)
  • 2-4 MiembroHogar (con cabeza de hogar + familiares)

Ejecución (desde la carpeta backend/):
    python seed_mi_casa3.py
"""

import os
import sys
import django
from datetime import date
from decimal import Decimal
from seed_setup import setup_django_path

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
setup_django_path()
django.setup()

from infrastructure.database.models import (
    Programa,
    Etapa,
    Ciudadano,
    Postulacion,
    GestionHogarEtapa1,
    MiembroHogar,
)

# ── Helpers ───────────────────────────────────────────────────────────────── #

def ok(msg):  print(f'  ✅ {msg}')
def info(msg): print(f'  ℹ️  {msg}')


# ── Obtener programa y etapa ─────────────────────────────────────────────── #

try:
    programa = Programa.objects.get(nombre='Mi casa3')
except Programa.DoesNotExist:
    print('❌ No se encontró el programa "Mi casa3". Verifica que exista en la BD.')
    sys.exit(1)

try:
    etapa = Etapa.objects.get(programa=programa, numero_etapa=1)
except Etapa.DoesNotExist:
    print('❌ No se encontró la Etapa 1 del programa "Mi casa3".')
    sys.exit(1)

print(f'📋 Programa: {programa.nombre} (id={programa.id})')
print(f'📋 Etapa: #{etapa.numero_etapa} — {etapa.modulo_principal} (id={etapa.id})')
print()

# ── Datos de las 10 postulaciones ─────────────────────────────────────────── #

POSTULACIONES = [
    # ── 1. Familia Caicedo Muñoz ──────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0001',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76301001',
            'primer_nombre': 'Jorge',
            'segundo_nombre': 'Enrique',
            'primer_apellido': 'Caicedo',
            'segundo_apellido': 'Muñoz',
            'fecha_nacimiento': date(1980, 3, 15),
            'sexo': 'MASCULINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3216549870',
            'correo_electronico': 'jorge.caicedo@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 4',
            'barrio_vereda': 'Barrio Bolívar',
            'direccion': 'Cra 9 # 4-52',
            'estrato': '2',
            'es_propietario': True,
            'numero_predial': '19001000000400041234500',
            'matricula_inmobiliaria': '120-45678',
            'avaluo_catastral': '45000000',
            'numero_matricula_agua': 'AC-2024-001234',
            'numero_contrato_energia': 'CE-2024-005678',
            'tiempo_residencia': '12 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76301001',
                'primer_nombre': 'Jorge',
                'segundo_nombre': 'Enrique',
                'primer_apellido': 'Caicedo',
                'segundo_apellido': 'Muñoz',
                'fecha_nacimiento': date(1980, 3, 15),
                'parentesco': 'PADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('1400000'),
                'fuente_ingresos': 'Comercio informal',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('28.50'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76401102',
                'primer_nombre': 'Sandra',
                'segundo_nombre': 'Milena',
                'primer_apellido': 'Muñoz',
                'segundo_apellido': 'Velasco',
                'fecha_nacimiento': date(1983, 8, 22),
                'parentesco': 'CONYUGE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Técnico',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1200000'),
                'fuente_ingresos': 'Trabajo en almacén',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('28.50'),
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900101',
                'primer_nombre': 'Sebastián',
                'segundo_nombre': '',
                'primer_apellido': 'Caicedo',
                'segundo_apellido': 'Muñoz',
                'fecha_nacimiento': date(2010, 5, 12),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria incompleta',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('28.50'),
            },
        ],
    },

    # ── 2. Familia Ordóñez Paz ────────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0002',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76302002',
            'primer_nombre': 'María',
            'segundo_nombre': 'del Carmen',
            'primer_apellido': 'Ordóñez',
            'segundo_apellido': 'Paz',
            'fecha_nacimiento': date(1975, 11, 30),
            'sexo': 'FEMENINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3157894561',
            'correo_electronico': 'maria.ordonez@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 7',
            'barrio_vereda': 'Barrio Los Hoyos',
            'direccion': 'Calle 15 # 2-18',
            'estrato': '1',
            'es_propietario': True,
            'numero_predial': '19001000000700071234500',
            'matricula_inmobiliaria': '120-52341',
            'avaluo_catastral': '32000000',
            'numero_matricula_agua': 'AC-2024-002345',
            'numero_contrato_energia': 'CE-2024-006789',
            'tiempo_residencia': '20 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': True,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76302002',
                'primer_nombre': 'María',
                'segundo_nombre': 'del Carmen',
                'primer_apellido': 'Ordóñez',
                'segundo_apellido': 'Paz',
                'fecha_nacimiento': date(1975, 11, 30),
                'parentesco': 'MADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Primaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('900000'),
                'fuente_ingresos': 'Venta de empanadas',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('18.30'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': True,
                'es_desplazado': True,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76402103',
                'primer_nombre': 'Héctor',
                'segundo_nombre': 'Fabio',
                'primer_apellido': 'Paz',
                'segundo_apellido': 'Guzmán',
                'fecha_nacimiento': date(1950, 2, 14),
                'parentesco': 'ABUELO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Sin escolaridad',
                'situacion_laboral': 'DESEMPLEADO',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('12.00'),
                'tiene_discapacidad': True,
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900202',
                'primer_nombre': 'Daniela',
                'segundo_nombre': 'Alejandra',
                'primer_apellido': 'Ordóñez',
                'segundo_apellido': 'Paz',
                'fecha_nacimiento': date(2008, 9, 5),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria incompleta',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('18.30'),
            },
            {
                'tipo_documento': 'REGISTRO_CIVIL',
                'numero_documento': '1061900203',
                'primer_nombre': 'Samuel',
                'segundo_nombre': '',
                'primer_apellido': 'Ordóñez',
                'segundo_apellido': 'Paz',
                'fecha_nacimiento': date(2019, 1, 20),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': '',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('18.30'),
            },
        ],
    },

    # ── 3. Familia Collazos Rivera ────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0003',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76303003',
            'primer_nombre': 'Edwin',
            'segundo_nombre': 'Arley',
            'primer_apellido': 'Collazos',
            'segundo_apellido': 'Rivera',
            'fecha_nacimiento': date(1988, 6, 10),
            'sexo': 'MASCULINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3001237890',
            'correo_electronico': 'edwin.collazos@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Timbío',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 6',
            'barrio_vereda': 'Barrio El Recuerdo',
            'direccion': 'Calle 73N # 9-35',
            'estrato': '2',
            'es_propietario': True,
            'numero_predial': '19001000000600061234500',
            'matricula_inmobiliaria': '120-63421',
            'avaluo_catastral': '38000000',
            'numero_matricula_agua': 'AC-2024-003456',
            'numero_contrato_energia': 'CE-2024-007890',
            'tiempo_residencia': '8 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76303003',
                'primer_nombre': 'Edwin',
                'segundo_nombre': 'Arley',
                'primer_apellido': 'Collazos',
                'segundo_apellido': 'Rivera',
                'fecha_nacimiento': date(1988, 6, 10),
                'parentesco': 'PADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Técnico',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1600000'),
                'fuente_ingresos': 'Obrero de construcción',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('32.10'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76403104',
                'primer_nombre': 'Yuri',
                'segundo_nombre': 'Vanessa',
                'primer_apellido': 'Bermúdez',
                'segundo_apellido': 'Solarte',
                'fecha_nacimiento': date(1990, 12, 3),
                'parentesco': 'COMPANERO_PERMANENTE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('800000'),
                'fuente_ingresos': 'Confecciones',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('32.10'),
            },
            {
                'tipo_documento': 'REGISTRO_CIVIL',
                'numero_documento': '1061900303',
                'primer_nombre': 'Matías',
                'segundo_nombre': '',
                'primer_apellido': 'Collazos',
                'segundo_apellido': 'Bermúdez',
                'fecha_nacimiento': date(2020, 4, 8),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': '',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('32.10'),
            },
        ],
    },

    # ── 4. Familia Samboni Chávez ─────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0004',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76304004',
            'primer_nombre': 'Luisa',
            'segundo_nombre': 'Fernanda',
            'primer_apellido': 'Samboni',
            'segundo_apellido': 'Chávez',
            'fecha_nacimiento': date(1992, 4, 25),
            'sexo': 'FEMENINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3124567890',
            'correo_electronico': 'luisa.samboni@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 9',
            'barrio_vereda': 'Barrio María Oriente',
            'direccion': 'Manzana H Casa 12, María Oriente',
            'estrato': '1',
            'es_propietario': True,
            'numero_predial': '19001000000900091234500',
            'matricula_inmobiliaria': '120-78912',
            'avaluo_catastral': '28000000',
            'numero_matricula_agua': 'AC-2024-004567',
            'numero_contrato_energia': 'CE-2024-008901',
            'tiempo_residencia': '5 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76304004',
                'primer_nombre': 'Luisa',
                'segundo_nombre': 'Fernanda',
                'primer_apellido': 'Samboni',
                'segundo_apellido': 'Chávez',
                'fecha_nacimiento': date(1992, 4, 25),
                'parentesco': 'MADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('1000000'),
                'fuente_ingresos': 'Venta de frutas',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('20.75'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900404',
                'primer_nombre': 'Kevin',
                'segundo_nombre': 'Stiven',
                'primer_apellido': 'Samboni',
                'segundo_apellido': 'Chávez',
                'fecha_nacimiento': date(2012, 7, 19),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('20.75'),
            },
            {
                'tipo_documento': 'REGISTRO_CIVIL',
                'numero_documento': '1061900405',
                'primer_nombre': 'Isabella',
                'segundo_nombre': '',
                'primer_apellido': 'Samboni',
                'segundo_apellido': 'Chávez',
                'fecha_nacimiento': date(2018, 11, 2),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': '',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('20.75'),
            },
        ],
    },

    # ── 5. Familia Velasco Hurtado ────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0005',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76305005',
            'primer_nombre': 'Luis',
            'segundo_nombre': 'Alberto',
            'primer_apellido': 'Velasco',
            'segundo_apellido': 'Hurtado',
            'fecha_nacimiento': date(1970, 9, 18),
            'sexo': 'MASCULINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3209871234',
            'correo_electronico': 'luis.velasco@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'El Tambo',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'RURAL',
            'tipo_predio': 'Finca',
            'comuna': '',
            'barrio_vereda': 'Vereda Quintana',
            'direccion': 'Kilómetro 5 vía Popayán-Coconuco',
            'estrato': '1',
            'es_propietario': True,
            'numero_predial': '19001000001000101234500',
            'matricula_inmobiliaria': '120-89123',
            'avaluo_catastral': '22000000',
            'numero_matricula_agua': '',
            'numero_contrato_energia': 'CE-2024-009012',
            'tiempo_residencia': '25 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76305005',
                'primer_nombre': 'Luis',
                'segundo_nombre': 'Alberto',
                'primer_apellido': 'Velasco',
                'segundo_apellido': 'Hurtado',
                'fecha_nacimiento': date(1970, 9, 18),
                'parentesco': 'PADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Primaria incompleta',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('750000'),
                'fuente_ingresos': 'Agricultura',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('15.20'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': True,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76405106',
                'primer_nombre': 'Carmen',
                'segundo_nombre': 'Rosa',
                'primer_apellido': 'Hurtado',
                'segundo_apellido': 'Jiménez',
                'fecha_nacimiento': date(1972, 1, 6),
                'parentesco': 'CONYUGE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('500000'),
                'fuente_ingresos': 'Cría de gallinas',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('15.20'),
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76505207',
                'primer_nombre': 'Andrés',
                'segundo_nombre': 'Felipe',
                'primer_apellido': 'Velasco',
                'segundo_apellido': 'Hurtado',
                'fecha_nacimiento': date(2000, 3, 28),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'DESEMPLEADO',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('15.20'),
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900505',
                'primer_nombre': 'Marisol',
                'segundo_nombre': '',
                'primer_apellido': 'Velasco',
                'segundo_apellido': 'Hurtado',
                'fecha_nacimiento': date(2007, 12, 14),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria incompleta',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('15.20'),
            },
        ],
    },

    # ── 6. Familia Solarte Erazo ──────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0006',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76306006',
            'primer_nombre': 'Gloria',
            'segundo_nombre': 'Patricia',
            'primer_apellido': 'Solarte',
            'segundo_apellido': 'Erazo',
            'fecha_nacimiento': date(1985, 2, 8),
            'sexo': 'FEMENINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3178901234',
            'correo_electronico': 'gloria.solarte@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 5',
            'barrio_vereda': 'Barrio La Esmeralda',
            'direccion': 'Cra 17 # 22-45',
            'estrato': '2',
            'es_propietario': True,
            'numero_predial': '19001000000500051234500',
            'matricula_inmobiliaria': '120-34567',
            'avaluo_catastral': '40000000',
            'numero_matricula_agua': 'AC-2024-006789',
            'numero_contrato_energia': 'CE-2024-010123',
            'tiempo_residencia': '10 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76306006',
                'primer_nombre': 'Gloria',
                'segundo_nombre': 'Patricia',
                'primer_apellido': 'Solarte',
                'segundo_apellido': 'Erazo',
                'fecha_nacimiento': date(1985, 2, 8),
                'parentesco': 'MADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Técnico',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1500000'),
                'fuente_ingresos': 'Auxiliar contable',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('30.00'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76406107',
                'primer_nombre': 'Carlos',
                'segundo_nombre': 'Hernán',
                'primer_apellido': 'Erazo',
                'segundo_apellido': 'López',
                'fecha_nacimiento': date(1983, 5, 17),
                'parentesco': 'COMPANERO_PERMANENTE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('1300000'),
                'fuente_ingresos': 'Mototaxismo',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('30.00'),
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900606',
                'primer_nombre': 'Valentina',
                'segundo_nombre': '',
                'primer_apellido': 'Solarte',
                'segundo_apellido': 'Erazo',
                'fecha_nacimiento': date(2011, 10, 30),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('30.00'),
            },
        ],
    },

    # ── 7. Familia Mosquera Caicedo ───────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0007',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76307007',
            'primer_nombre': 'Diego',
            'segundo_nombre': 'Fernando',
            'primer_apellido': 'Mosquera',
            'segundo_apellido': 'Caicedo',
            'fecha_nacimiento': date(1978, 7, 5),
            'sexo': 'MASCULINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3054321987',
            'correo_electronico': 'diego.mosquera@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Cajibío',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 8',
            'barrio_vereda': 'Barrio Lomas de Granada',
            'direccion': 'Manzana F Casa 8, Lomas de Granada',
            'estrato': '1',
            'es_propietario': True,
            'numero_predial': '19001000000800081234500',
            'matricula_inmobiliaria': '120-56789',
            'avaluo_catastral': '30000000',
            'numero_matricula_agua': 'AC-2024-007890',
            'numero_contrato_energia': 'CE-2024-011234',
            'tiempo_residencia': '15 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': True,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76307007',
                'primer_nombre': 'Diego',
                'segundo_nombre': 'Fernando',
                'primer_apellido': 'Mosquera',
                'segundo_apellido': 'Caicedo',
                'fecha_nacimiento': date(1978, 7, 5),
                'parentesco': 'PADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('1100000'),
                'fuente_ingresos': 'Carpintería',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('22.40'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': True,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76407108',
                'primer_nombre': 'Ana',
                'segundo_nombre': 'Milena',
                'primer_apellido': 'Caicedo',
                'segundo_apellido': 'Burbano',
                'fecha_nacimiento': date(1980, 4, 22),
                'parentesco': 'CONYUGE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria completa',
                'situacion_laboral': 'DESEMPLEADO',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('22.40'),
                'tiene_discapacidad': True,
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900707',
                'primer_nombre': 'Santiago',
                'segundo_nombre': '',
                'primer_apellido': 'Mosquera',
                'segundo_apellido': 'Caicedo',
                'fecha_nacimiento': date(2009, 8, 15),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria incompleta',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('22.40'),
            },
            {
                'tipo_documento': 'REGISTRO_CIVIL',
                'numero_documento': '1061900708',
                'primer_nombre': 'Sara',
                'segundo_nombre': 'Lucía',
                'primer_apellido': 'Mosquera',
                'segundo_apellido': 'Caicedo',
                'fecha_nacimiento': date(2017, 6, 3),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': '',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('22.40'),
            },
        ],
    },

    # ── 8. Familia Zúñiga Rengifo ─────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0008',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76308008',
            'primer_nombre': 'Nelly',
            'segundo_nombre': 'Esperanza',
            'primer_apellido': 'Zúñiga',
            'segundo_apellido': 'Rengifo',
            'fecha_nacimiento': date(1968, 12, 20),
            'sexo': 'FEMENINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3167890123',
            'correo_electronico': 'nelly.zuniga@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 3',
            'barrio_vereda': 'Barrio El Cadillal',
            'direccion': 'Calle 5 # 11-28',
            'estrato': '2',
            'es_propietario': True,
            'numero_predial': '19001000000300031234500',
            'matricula_inmobiliaria': '120-23456',
            'avaluo_catastral': '42000000',
            'numero_matricula_agua': 'AC-2024-008901',
            'numero_contrato_energia': 'CE-2024-012345',
            'tiempo_residencia': '30 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76308008',
                'primer_nombre': 'Nelly',
                'segundo_nombre': 'Esperanza',
                'primer_apellido': 'Zúñiga',
                'segundo_apellido': 'Rengifo',
                'fecha_nacimiento': date(1968, 12, 20),
                'parentesco': 'MADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Primaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('850000'),
                'fuente_ingresos': 'Venta de arepas',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('19.80'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76408109',
                'primer_nombre': 'Oscar',
                'segundo_nombre': 'Javier',
                'primer_apellido': 'Zúñiga',
                'segundo_apellido': 'Rengifo',
                'fecha_nacimiento': date(1992, 3, 14),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Universidad incompleta',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1300000'),
                'fuente_ingresos': 'Mensajero',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('19.80'),
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76508210',
                'primer_nombre': 'Diana',
                'segundo_nombre': 'Marcela',
                'primer_apellido': 'Zúñiga',
                'segundo_apellido': 'Rengifo',
                'fecha_nacimiento': date(1995, 7, 1),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Técnico',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1200000'),
                'fuente_ingresos': 'Peluquería',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('19.80'),
            },
        ],
    },

    # ── 9. Familia Gutiérrez Olave ────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0009',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76309009',
            'primer_nombre': 'Hernando',
            'segundo_nombre': '',
            'primer_apellido': 'Gutiérrez',
            'segundo_apellido': 'Olave',
            'fecha_nacimiento': date(1982, 10, 1),
            'sexo': 'MASCULINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3101234567',
            'correo_electronico': 'hernando.gutierrez@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Piendamó',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'URBANA',
            'tipo_predio': 'Casa',
            'comuna': 'Comuna 2',
            'barrio_vereda': 'Barrio Las Américas',
            'direccion': 'Cra 6A # 35N-12',
            'estrato': '2',
            'es_propietario': True,
            'numero_predial': '19001000000200021234500',
            'matricula_inmobiliaria': '120-12345',
            'avaluo_catastral': '36000000',
            'numero_matricula_agua': 'AC-2024-009012',
            'numero_contrato_energia': 'CE-2024-013456',
            'tiempo_residencia': '7 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76309009',
                'primer_nombre': 'Hernando',
                'segundo_nombre': '',
                'primer_apellido': 'Gutiérrez',
                'segundo_apellido': 'Olave',
                'fecha_nacimiento': date(1982, 10, 1),
                'parentesco': 'PADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Técnico',
                'situacion_laboral': 'EMPLEADO',
                'ingresos_mensuales': Decimal('1700000'),
                'fuente_ingresos': 'Conductor de bus urbano',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('35.60'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': False,
                'es_desplazado': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76409110',
                'primer_nombre': 'Claudia',
                'segundo_nombre': 'Marcela',
                'primer_apellido': 'Olave',
                'segundo_apellido': 'Torres',
                'fecha_nacimiento': date(1986, 6, 19),
                'parentesco': 'CONYUGE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('950000'),
                'fuente_ingresos': 'Venta de comidas rápidas',
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('35.60'),
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061900909',
                'primer_nombre': 'Miguel',
                'segundo_nombre': 'Ángel',
                'primer_apellido': 'Gutiérrez',
                'segundo_apellido': 'Olave',
                'fecha_nacimiento': date(2013, 2, 28),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'B',
                'puntaje_sisben': Decimal('35.60'),
            },
        ],
    },

    # ── 10. Familia Bolaños Cerón ─────────────────────────────────────────
    {
        'radicado': 'RAD-MC3-202603-0010',
        'titular': {
            'tipo_documento': 'CEDULA_CIUDADANIA',
            'numero_documento': '76310010',
            'primer_nombre': 'Rosa',
            'segundo_nombre': 'Elena',
            'primer_apellido': 'Bolaños',
            'segundo_apellido': 'Cerón',
            'fecha_nacimiento': date(1990, 5, 12),
            'sexo': 'FEMENINO',
            'nacionalidad': 'Colombiana',
            'telefono': '3189012345',
            'correo_electronico': 'rosa.bolanos@correo.com',
            'departamento_nacimiento': 'Cauca',
            'municipio_nacimiento': 'Popayán',
        },
        'predio': {
            'departamento': 'Cauca',
            'municipio': 'Popayán',
            'zona': 'RURAL',
            'tipo_predio': 'Casa',
            'comuna': '',
            'barrio_vereda': 'Vereda Torres',
            'direccion': 'Kilómetro 3 vía Popayán-Timbío, sector Torres',
            'estrato': '1',
            'es_propietario': True,
            'numero_predial': '19001000001100111234500',
            'matricula_inmobiliaria': '120-91234',
            'avaluo_catastral': '25000000',
            'numero_matricula_agua': '',
            'numero_contrato_energia': 'CE-2024-014567',
            'tiempo_residencia': '4 años',
            'tiene_dependientes': True,
            'personas_con_discapacidad_hogar': False,
            'acepta_terminos_condiciones': True,
        },
        'miembros': [
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76310010',
                'primer_nombre': 'Rosa',
                'segundo_nombre': 'Elena',
                'primer_apellido': 'Bolaños',
                'segundo_apellido': 'Cerón',
                'fecha_nacimiento': date(1990, 5, 12),
                'parentesco': 'MADRE',
                'es_cabeza_hogar': True,
                'nivel_educativo': 'Secundaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('700000'),
                'fuente_ingresos': 'Cosecha de café',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('16.50'),
                'tiene_discapacidad': False,
                'es_victima_conflicto': True,
                'es_desplazado': True,
                'es_firmante_paz': False,
            },
            {
                'tipo_documento': 'CEDULA_CIUDADANIA',
                'numero_documento': '76410111',
                'primer_nombre': 'Fabián',
                'segundo_nombre': 'Andrés',
                'primer_apellido': 'Cerón',
                'segundo_apellido': 'Mera',
                'fecha_nacimiento': date(1988, 11, 8),
                'parentesco': 'COMPANERO_PERMANENTE',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria completa',
                'situacion_laboral': 'INDEPENDIENTE',
                'ingresos_mensuales': Decimal('800000'),
                'fuente_ingresos': 'Jornalero agrícola',
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('16.50'),
            },
            {
                'tipo_documento': 'TARJETA_IDENTIDAD',
                'numero_documento': '1061901010',
                'primer_nombre': 'Juliana',
                'segundo_nombre': '',
                'primer_apellido': 'Bolaños',
                'segundo_apellido': 'Cerón',
                'fecha_nacimiento': date(2014, 8, 25),
                'parentesco': 'HIJA',
                'es_cabeza_hogar': False,
                'nivel_educativo': 'Primaria',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('16.50'),
            },
            {
                'tipo_documento': 'REGISTRO_CIVIL',
                'numero_documento': '1061901011',
                'primer_nombre': 'Tomás',
                'segundo_nombre': '',
                'primer_apellido': 'Bolaños',
                'segundo_apellido': 'Cerón',
                'fecha_nacimiento': date(2021, 3, 10),
                'parentesco': 'HIJO',
                'es_cabeza_hogar': False,
                'nivel_educativo': '',
                'situacion_laboral': '',
                'ingresos_mensuales': None,
                'pertenece_sisben': True,
                'grupo_sisben': 'A',
                'puntaje_sisben': Decimal('16.50'),
            },
        ],
    },
]


# ── Inserción ─────────────────────────────────────────────────────────────── #

created = 0
skipped = 0

for idx, data in enumerate(POSTULACIONES, 1):
    radicado = data['radicado']

    if GestionHogarEtapa1.objects.filter(numero_radicado=radicado).exists():
        info(f'[{idx}/10] {radicado} ya existe → omitido')
        skipped += 1
        continue

    t = data['titular']

    # Ciudadano titular
    ciudadano, _ = Ciudadano.objects.get_or_create(
        tipo_documento=t['tipo_documento'],
        numero_documento=t['numero_documento'],
        defaults={
            'primer_nombre': t['primer_nombre'],
            'segundo_nombre': t.get('segundo_nombre', ''),
            'primer_apellido': t['primer_apellido'],
            'segundo_apellido': t.get('segundo_apellido', ''),
            'fecha_nacimiento': t['fecha_nacimiento'],
            'sexo': t['sexo'],
            'nacionalidad': t['nacionalidad'],
            'telefono': t.get('telefono', ''),
            'correo_electronico': t.get('correo_electronico', ''),
            'departamento_nacimiento': t.get('departamento_nacimiento', ''),
            'municipio_nacimiento': t.get('municipio_nacimiento', ''),
        },
    )

    # Postulación (siempre EN_REVISION)
    postulacion = Postulacion.objects.create(
        programa=programa,
        etapa_actual=etapa,
        estado='EN_REVISION',
    )

    # GestionHogarEtapa1
    p = data['predio']
    gestion = GestionHogarEtapa1.objects.create(
        numero_radicado=radicado,
        postulacion=postulacion,
        etapa=etapa,
        ciudadano=ciudadano,
        departamento=p['departamento'],
        municipio=p['municipio'],
        zona=p['zona'],
        tipo_predio=p.get('tipo_predio', ''),
        comuna=p.get('comuna', ''),
        barrio_vereda=p.get('barrio_vereda', ''),
        direccion=p['direccion'],
        estrato=p.get('estrato', ''),
        es_propietario=p.get('es_propietario'),
        numero_predial=p.get('numero_predial', ''),
        matricula_inmobiliaria=p.get('matricula_inmobiliaria', ''),
        avaluo_catastral=p.get('avaluo_catastral', ''),
        numero_matricula_agua=p.get('numero_matricula_agua', ''),
        numero_contrato_energia=p.get('numero_contrato_energia', ''),
        tiempo_residencia=p.get('tiempo_residencia', ''),
        tiene_dependientes=p.get('tiene_dependientes'),
        personas_con_discapacidad_hogar=p.get('personas_con_discapacidad_hogar'),
        acepta_terminos_condiciones=p.get('acepta_terminos_condiciones', False),
    )

    # Miembros del hogar
    for m in data['miembros']:
        MiembroHogar.objects.create(
            postulacion=gestion,
            tipo_documento=m['tipo_documento'],
            numero_documento=m['numero_documento'],
            primer_nombre=m['primer_nombre'],
            segundo_nombre=m.get('segundo_nombre', ''),
            primer_apellido=m['primer_apellido'],
            segundo_apellido=m.get('segundo_apellido', ''),
            fecha_nacimiento=m['fecha_nacimiento'],
            parentesco=m['parentesco'],
            es_cabeza_hogar=m.get('es_cabeza_hogar', False),
            nivel_educativo=m.get('nivel_educativo', ''),
            situacion_laboral=m.get('situacion_laboral', ''),
            ingresos_mensuales=m.get('ingresos_mensuales'),
            fuente_ingresos=m.get('fuente_ingresos', ''),
            pertenece_sisben=m.get('pertenece_sisben'),
            grupo_sisben=m.get('grupo_sisben', ''),
            puntaje_sisben=m.get('puntaje_sisben'),
            tiene_discapacidad=m.get('tiene_discapacidad', False),
            es_victima_conflicto=m.get('es_victima_conflicto', False),
            es_desplazado=m.get('es_desplazado', False),
            es_firmante_paz=m.get('es_firmante_paz', False),
        )

    ok(
        f'[{idx}/10] {radicado} → '
        f'{t["primer_nombre"]} {t["primer_apellido"]} | '
        f'EN_REVISION | {len(data["miembros"])} miembro(s)'
    )
    created += 1

print()
print('─' * 55)
print(f'✅ Resumen: {created} postulación(es) creada(s), {skipped} omitida(s)')
print(f'📋 Programa: {programa.nombre} (id={programa.id})')
print(f'🔍 Verificar: GET /api/postulaciones/registro-hogar/')
