# Generated by Django 6.0.2 on 2026-03-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioSistema',
        ),
    ]
